const Map<String, String> langCodes = {
  "Amharic": "am",
  "Arabic": "ar",
  "Basque": "eu",
  "Bengali": "bn",
  "English (UK)": "en-GB",
  "Portuguese (Brazil)": "pt-BR",
  "Bulgarian": "bg",
  "Catalan": "ca",
  "Cherokee": "chr",
  "Croatian": "hr",
  "Czech": "cs",
  "Danish": "da",
  "Dutch": "nl",
  "English (US)": "en",
  "Estonian": "et",
  "Filipino": "fil",
  "Finnish": "fi",
  "French": "fr",
  "German": "de",
  "Greek": "el",
  "Gujarati": "gu",
  "Hebrew": "iw",
  "Hindi": "hi",
  "Hungarian": "hu",
  "Icelandic": "is",
  "Indonesian": "id",
  "Italian": "it",
  "Japanese": "ja",
  "Kannada": "kn",
  "Korean": "ko",
  "Latvian": "lv",
  "Lithuanian": "lt",
  "Malay": "ms",
  "Malayalam": "ml",
  "Marathi": "mr",
  "Norwegian": "no",
  "Polish": "pl",
  "Portuguese (Portugal)": "pt-PT",
  "Romanian": "ro",
  "Russian": "ru",
  "Serbian": "sr",
  "Chinese (PRC)": "zh-CN",
  "Slovak": "sk",
  "Slovenian": "sl",
  "Spanish": "es",
  "Swahili": "sw",
  "Swedish": "sv",
  "Tamil": "ta",
  "Telugu": "te",
  "Thai": "th",
  "Chinese (Taiwan)": "zh-TW",
  "Turkish": "tr",
  "Urdu": "ur",
  "Ukrainian": "uk",
  "Vietnamese": "vi",
  "Welsh": "cy"
};

const List<String> langNames = [
  "Amharic",
  "Arabic",
  "Basque",
  "Bengali",
  "English (UK)",
  "Portuguese (Brazil)",
  "Bulgarian",
  "Catalan",
  "Cherokee",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "English (US)",
  "Estonian",
  "Filipino",
  "Finnish",
  "French",
  "German",
  "Greek",
  "Gujarati",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Icelandic",
  "Indonesian",
  "Italian",
  "Japanese",
  "Kannada",
  "Korean",
  "Latvian",
  "Lithuanian",
  "Malay",
  "Malayalam",
  "Marathi",
  "Norwegian",
  "Polish",
  "Portuguese (Portugal)",
  "Romanian",
  "Russian",
  "Serbian",
  "Chinese (PRC)",
  "Slovak",
  "Slovenian",
  "Spanish",
  "Swahili",
  "Swedish",
  "Tamil",
  "Telugu",
  "Thai",
  "Chinese (Taiwan)",
  "Turkish",
  "Urdu",
  "Ukrainian",
  "Vietnamese",
  "Welsh"
];
